[package]
name = "dns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
mongodb = { version = "2.8.2", features = ["sync"], default-features = false }
rand = "0.8.5"
rocket = { version = "0.5.0", features = ["json"] }
rocket-governor = { version = "0.2.0-rc.1", features = ["limit_info"] }
serde = "1.0.201"