[package]
name = "dns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
futures = "0.3.30"
mongodb = { version = "2.8.2", features = ["sync"], default-features = false }
rand = "0.8.5"
rocket = { version = "0.5.0", features = ["json"] }
rocket_sync_db_pools = "0.1.0"
serde = "1.0.201"
